default[:runit][:sv_bin] = "/opt/graylog/embedded/bin/sv"
default[:runit][:chpst_bin] = "/opt/graylog/embedded/bin/chpst"
default[:runit][:service_dir] = "/opt/graylog/service"
default[:runit][:sv_dir] = "/opt/graylog/sv"
default[:runit][:sv_loggelfd_version] = "0.2.1"
